{
 "title": "ICA0002",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "DNS queries",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(bind_incoming_queries_total[5m])"
    }
   ]
  },
  {
   "title": "infra01 CPU usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_cpu{instance=\"infra01.peril.ttu:9100\"}[5m])"
    }
   ]
  },
  {
   "title": "infra02 CPU usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_cpu{instance=\"infra02.peril.ttu:9100\"}[5m])"
    }
   ]
  },
  {
   "title": "MySQL status",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "mysql_up" }
   ]
  },
  {
   "title": "HAProxy status",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "haproxy_up" }
   ]
  },
  {
   "title": "Prometheus query durations",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(prometheus_engine_query_duration_seconds[5m])"
    }
   ]
  },
  {
   "title": "Syslog error count (TODO: get it below 5/s)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "syslog",
     "select": [
      [
       { "params": [ "severity_code" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "severity", "operator": "=", "value": "err" }
     ]
    }
   ]
  },
  {
   "title": "HAProxy exporter CSV parse failures",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(haproxy_exporter_csv_parse_failures[5m])"
    }
   ]
  },
  {
   "title": "bind master",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "bind_up{instance=\"infra01.peril.ttu:9119\"}"
    }
   ]
  },
  {
   "title": "bind slave",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "bind_up{instance=\"infra02.peril.ttu:9119\"}"
    }
   ]
  }
 ]
}