---
- name: Global configs
  hosts: linux
  become: yes
  roles:
  - dns
  - syslog
  - node_exporter

- name: Set up infra01
  hosts: infra01
  become: yes
  roles:
  - wordpress
  - telegraf

- name: Set up infra02
  hosts: infra02
  become: yes
  roles:
  - mysql
  - influxdb
  - prometheus
  - grafana
  - haproxy

- post_tasks:
  - name: Remove unneeded Wordpress containers
    docker_container:
      name: 'wp{{ item }}'
      state: absent
    loop: "{{ range(wp_max_instances-1, wp_instance_count-1, -1) | list }}"
