---
forwarders:
  - 8.8.8.8
  - 1.1.1.1
  - 9.9.9.10

allowed_nets:
  - 192.168.56.0/24
  - 10.0.2.0/24
  - localhost

startup: peril.ttu

dns_vars:
  - name: "{{ startup }}."
    type: NS
    addr: ns1
  - name: "{{ startup }}."
    type: NS
    addr: ns2
  - name: infra01
    type: A
    addr: 192.168.56.50
  - name: infra02
    type: A
    addr: 192.168.56.51
  - name: ns1
    type: A
    addr: 192.168.56.50
  - name: ns2
    type: A
    addr: 192.168.56.51
  - name: prometheus
    type: CNAME
    addr: infra02
  - name: grafana
    type: CNAME
    addr: infra01
  - name: influxdb
    type: CNAME
    addr: infra02
  - name: mysql
    type: CNAME
    addr: infra02
  - name: www
    type: CNAME
    addr: infra02
  - name: telegraf
    type: CNAME
    addr: infra01
