---
- name: Network setup
  hosts: all
  remote_user: user
  become: yes
  tasks:
  - name: Configure netplan
    template:
      src: files/netplan.yaml
      dest: /etc/netplan/50-static-vbox.yaml
    notify:
    - netplan apply

  - name: Disable systemd-resolved
    service:
      name: systemd-resolved
      state: stopped
      enabled: no

  - name: Configure DNS
    copy:
      content: "nameserver 127.0.0.53\nnameserver 1.0.0.1\n"
      dest: /etc/resolv.conf

  handlers:
  - name:  netplan apply
    shell: netplan apply

