---
- import_playbook: ../auth/auth.yaml

- name: Network setup
  hosts: all
  remote_user: user
  become: yes
  tasks:
  - name: Configure netplan
    template:
      src: files/netplan.yaml
      dest: /etc/netplan/50-static-vbox.yaml
    notify:
    - netplan apply

  handlers:
  - name:  netplan apply
    shell: netplan apply

- name: Set up bind9
  hosts: all
  remote_user: user
  become: yes
  tasks:
  - name: Install bind
    apt:
      name: bind9

  - name: Configure bind options config
    template:
      src: files/named.conf.options.j2
      dest: /etc/bind/named.conf.options
    notify:
    - check bind conf
    - restart bind

  - name: Configure bind local config
    template:
      src: files/named.conf.local.j2
      dest: /etc/bind/named.conf.local
    notify:
    - check bind conf
    - restart bind

  - name: Update db hash
    when: dns_role == "master"
    copy:
      content: "{{ dns_vars|hash }}"
      dest: /etc/bind/db.peril.hash
    notify:
    - timestamp
    - check bind conf
    - db update
    - ptr db update
    - bind update

  handlers:
  - name: timestamp
    shell: date +%s
    register: ts

  - name:  check bind conf
    shell: named-checkconf

  - name: db update
    template:
      src: files/db.peril.j2
      dest: /etc/bind/db.peril

  - name: ptr db update
    template:
      src: files/db.peril.ptr.j2
      dest: /etc/bind/db.peril.ptr

  - name: check zone conf
    shell: "named-checkzone peril.ttu. /etc/bind/db.peril"

  - name: check reverse zone conf
    shell: "named-checkzone peril.ttu. /etc/bind/db.peril.ptr"

  - name: restart bind
    service:
      name: bind9
      state: restarted

  - name: bind update
    shell: rndc reload
