---
- import_playbook: ../auth/auth.yaml
- name: Lab 2 playbook
  hosts: ubuntu
  remote_user: user
  become: yes
  tasks:
  - name: Generate keys for user
    user:
      name: user
      generate_ssh_key: yes

  - name: Create sysadmins group
    group:
      name: sysadmins

  - name: Add romankuchin user
    user:
      name: romankuchin
      append: yes
      groups: sysadmins,adm

  - name: Add hudolejev user
    user:
      name: hudolejev
      append: yes
      groups: sysadmins,adm

  - name: Add romankuchin key
    authorized_key:
      user: romankuchin
      key: https://github.com/romankuchin.keys

  - name: Add hudolejev key
    authorized_key:
      user: hudolejev
      key: https://github.com/hudolejev.keys

  - name: Get list of processes
    shell: "ps -e"
    register: procs

  - name: List processes
    debug:
      var: procs.stdout_lines
