---
- name: Set up bind9
  hosts: dns
  remote_user: user
  become: yes
  tasks:
  - name: Install bind
    apt:
      name: bind9

  - name: Configure bind options config
    template:
      src: files/named.conf.options.j2
      dest: /etc/bind/named.conf.options
    notify:
    - check bind conf
    - restart bind

  - name: Configure bind local config
    template:
      src: files/named.conf.local.j2
      dest: /etc/bind/named.conf.local
    notify:
    - check bind conf
    - restart bind

  - name: Update db hash
#    when: dns_role == "master"
    when: "inventory_hostname == 'master'"
    copy:
      content: "{{ dns_vars|hash }}\n"
      dest: "/etc/bind/db.{{ startup }}.hash"
    notify:
    - timestamp
    - check bind conf
    - db update
    - ptr db update
    - bind update
    - check zone conf
    - check reverse zone conf

  handlers:
  - name: timestamp
    shell: date +%s
    register: ts

  - name:  check bind conf
    shell: named-checkconf

  - name: db update
    template:
      src: files/db.startup.j2
      dest: "/etc/bind/db.{{ startup }}"

  - name: ptr db update
    template:
      src: files/db.startup.ptr.j2
      dest: "/etc/bind/db.{{ startup }}.ptr"

  - name: check zone conf
    shell: "named-checkzone {{ startup }}. /etc/bind/db.{{ startup }}"

  - name: check reverse zone conf
    shell: "named-checkzone 56.168.192.in-addr.arpa /etc/bind/db.{{ startup }}.ptr"

  - name: restart bind
    service:
      name: bind9
      state: restarted

  - name: bind update
    shell: rndc reload
