---
- name: Lab 4 playbook - Web server
  hosts: frontend
  remote_user: user
  become: yes

  vars_files:
    - files/wp_vars.yml

  tasks:
  - name: Install required packages
    apt:
      name: "{{ packages }}"
    vars:
      packages:
      -  apache2
      -  php
      -  mysql-client
      -  php-mysql
      -  wordpress

  - name: Add apache site conf for WordPress
    copy:
      src: files/wordpress.conf
      dest: /etc/apache2/sites-available/wordpress.conf
      mode: '0644'
    notify:
    - reload wordpress

  - name: Add WordPress conf file
    template:
      src: files/config-sql.php
      dest: '/etc/wordpress/config-{{ ansible_host }}.php'
      owner: www-data
      group: www-data
      mode: '0400'
    notify:
    - reload wordpress

  - name: Disable default site
    file:
      path: /etc/apache2/sites-enabled/000-default.conf
      state: absent
    notify:
    - reload wordpress

  - name: Enable WordPress
    file:
      path: /etc/apache2/sites-enabled/wordpress.conf
      state: link
      src: /etc/apache2/sites-available/wordpress.conf
    notify:
    - reload wordpress

  handlers:
  - name: reload apache
    service:
      name: apache2
      state: reloaded

- name: Lab 4 playbook - SQL server
  hosts: database
  remote_user: user
  become: yes
  vars_files:
    - files/wp_vars.yml
  tasks:
  - name: Install packages
    apt:
      name: "{{ packages }}"
    vars:
      packages:
      -  mysql-server
      -  python-pymysql

  - name: Create WordPress database
    mysql_db:
      name: wordpress
      config_file: /etc/mysql/debian.cnf

  - name: Add WordPress SQL user
    mysql_user:
      name: wordpress
      password: "{{ sql_pass }}"
      host: "{{ web_host }}"
      priv: "wordpress.*:SELECT,INSERT,UPDATE,DELETE,CREATE,DROP,ALTER"
      config_file: /etc/mysql/debian.cnf

  - name: Allow external MySQL connections
    replace:
      path: /etc/mysql/mysql.conf.d/mysqld.cnf
      regexp: '^(bind-address.*)'
      replace: '# \1'
    notify:
    - restart mysqld

  handlers:
  - name: restart mysqld
    service:
      name: mysql
      state: restarted
