- name: Install packages
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - mysql-server
    - python3-pymysql

- name: Create WordPress database
  mysql_db:
    name: wordpress
    config_file: /etc/mysql/debian.cnf

- name: Add WordPress SQL user
  mysql_user:
    name: wordpress
    password: "{{ sql_pass }}"
    host: '%'
    priv: "wordpress.*:SELECT,INSERT,UPDATE,DELETE,CREATE,DROP,ALTER"
    config_file: /etc/mysql/debian.cnf

- name: Allow external MySQL connections
  replace:
    path: /etc/mysql/mysql.conf.d/mysqld.cnf
    regexp: '^(bind-address.*)'
    replace: '# \1'
  notify:
  - restart mysqld
