---
- name: Set up DNS servers
  hosts: dns
  remote_user: user
  become: yes
  roles:
  - dns

- name: Nodes
  hosts: linux
  remote_user: user
  become: yes
  roles:
  - node

- name: Prometheus
  hosts: prometheus
  remote_user: user
  become: yes
  roles:
  - prometheus

- name: Wordpress
  hosts: web1
  remote_user: user
  become: yes
  roles:
  - wordpress

- name: MySQL
  hosts: db1
  remote_user: user
  become: yes
  roles:
  - mysql

- name: Grafana
  hosts: infra01
  remote_user: user
  become: yes
  roles:
  - grafana
